/**
 * IPC result envelope and error codes.
 * All IPC handlers return IpcResult<T> — never throw across the IPC boundary.
 */

export enum EvidexErrorCode {
  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_INPUT = 'INVALID_INPUT',

  // Session
  SESSION_ALREADY_ACTIVE = 'SESSION_ALREADY_ACTIVE',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_NOT_ACTIVE = 'SESSION_NOT_ACTIVE',

  // Project
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_ALREADY_OPEN = 'PROJECT_ALREADY_OPEN',
  PROJECT_SIZE_EXCEEDED = 'PROJECT_SIZE_EXCEEDED',
  PROJECT_CORRUPTED = 'PROJECT_CORRUPTED',

  // Capture
  CAPTURE_FAILED = 'CAPTURE_FAILED',
  CAPTURE_NOT_FOUND = 'CAPTURE_NOT_FOUND',
  CAPTURE_PERMISSION_DENIED = 'CAPTURE_PERMISSION_DENIED',

  // Container
  CONTAINER_OPEN_FAILED = 'CONTAINER_OPEN_FAILED',
  CONTAINER_SAVE_FAILED = 'CONTAINER_SAVE_FAILED',
  CONTAINER_DECRYPT_FAILED = 'CONTAINER_DECRYPT_FAILED',
  CONTAINER_INTEGRITY_FAILED = 'CONTAINER_INTEGRITY_FAILED',

  // Template
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_BUILTIN_READONLY = 'TEMPLATE_BUILTIN_READONLY',

  // Export
  EXPORT_FAILED = 'EXPORT_FAILED',
  EXPORT_MISSING_REQUIRED_FIELDS = 'EXPORT_MISSING_REQUIRED_FIELDS',

  // Metrics import
  IMPORT_SCHEMA_MISMATCH = 'IMPORT_SCHEMA_MISMATCH',
  IMPORT_FILE_UNREADABLE = 'IMPORT_FILE_UNREADABLE',

  // Licence
  LICENCE_INVALID = 'LICENCE_INVALID',
  LICENCE_EXPIRED = 'LICENCE_EXPIRED',
  LICENCE_MACHINE_MISMATCH = 'LICENCE_MACHINE_MISMATCH',
  LICENCE_NETWORK_FAILED = 'LICENCE_NETWORK_FAILED',

  // Sign-off
  SIGNOFF_REJECT_REQUIRES_COMMENT = 'SIGNOFF_REJECT_REQUIRES_COMMENT',

  // Filesystem
  FS_WRITE_FAILED = 'FS_WRITE_FAILED',
  FS_READ_FAILED = 'FS_READ_FAILED',
  FS_PATH_INVALID = 'FS_PATH_INVALID',
  STORAGE_PATH_NOT_WRITABLE = 'STORAGE_PATH_NOT_WRITABLE',
  STORAGE_LIMIT_EXCEEDED = 'STORAGE_LIMIT_EXCEEDED',   // LO-04: hard 20MB cap

  // Shortcut
  SHORTCUT_CONFLICT = 'SHORTCUT_CONFLICT',

  // Generic
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export interface IpcError {
  code: EvidexErrorCode;
  message: string;
  fields?: Record<string, string>;
}

export type IpcResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: IpcError };
